### ISSUE TITLE
데이터셋 포맷 분석

### ISSUE THREAD

**Issue by februa22** [nlp-research/biaffine-attention-ndp#1]

**Comment by februa22** [comment]
UD-EWT 데이터셋도 PTB-SD 데이터셋 포맷과 동일하네요.
대신에 코멘트 라인(`#`으로 시작하는 라인)은 `continue`하도록 소스코드 수정해야 해요.
데이터셋 포맷에 대한 자세한 내용은 다음 내용 참고하세요:

Universal Dependencies English Web Treebank v2.2 -- 2018-04-15
https://github.com/UniversalDependencies/UD_English-EWT

This corpus is compatible with the CoNLL-U format defined for Universal
Dependencies. See:

   http://universaldependencies.github.io/docs/format.html

**Comment by bart2001** [comment]
코멘트 라인(#으로 시작하는 라인)에 대해서 continue하도록 수정하였습니다.
vocab.py, dataset.py

* dataset.py에서
self.lines_per_buffer = 0일 경우에만 동작하도록  (학습시 읽어들이는 파일 라인의 개수, 0일 경우 전부 읽도록 설정) 옵션만 사용할 계획이므로 if (self.lines_per_buffer > 0)에서 else 조건에 대해서만 continue하도록 추가하였습니다.

**Comment by bart2001** [comment]
GUM 데이터셋의 경우에는 인덱스 번호에 .이나 -가 없습니다.
https://github.com/UniversalDependencies/UD_English-GUM/tree/master

**Comment by bart2001** [comment]
k_means.py의 로직상의 문제이지 데이터포맷이 다른 것은 아닌 것 같습니다.
학습데이터 포맷은 분석이 되었으므로 이슈 종료합니다.
